/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package pl.mk5.polygonal.functional

import org.gradle.testkit.runner.GradleRunner
import spock.lang.Specification

class JavaYMLFunctionalTest extends Specification {
    def "can run task"() {
        given:
        def projectDir = new File("build/e2eTest")
        projectDir.deleteDir()
        projectDir.mkdirs()
        new File(projectDir, "code/java/org/example").mkdirs()
        new File(projectDir, "code/java/org/example/domain1/dto").mkdirs()
        new File(projectDir, "code/java/org/example/domain2/abc/defg").mkdirs()
        new File(projectDir, "code/java/org/example/domain2/abc/defg/Foo.java").write("public class Foo { }")
        new File(projectDir, "code/java/org/example/domain2/dto").mkdirs()
        new File(projectDir, "settings.gradle") << ""
        new File(projectDir, "polygon.yml") << """
polygon:
  public: -1
  packages:
    abc:
      required: true
      defg:
        public: -1
    dto:
      required: true
"""
        new File(projectDir, "build.gradle") << """
            plugins {
                id('java')
                id('pl.mk5.polygonal-architecture')
            }
            
            polygonalArchitecture {
                sourcesDir = file('code/java')
                basePackage = 'org.example'
                polygonTemplate = file('polygon.yml')
            }
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("verifyPolygons")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("Task :verifyPolygons")
        !result.output.contains("ConditionException")
    }
}
