/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.polygonal.functional

import org.gradle.testkit.runner.GradleRunner
import spock.lang.Specification

class KotlinFunctionalTest extends Specification {
    def "can run task"() {
        given:
        def projectDir = new File("build/e2eTest")
        projectDir.deleteDir()
        projectDir.mkdirs()
        new File(projectDir, "code/kotlin/org/example/c").mkdirs()
        new File(projectDir, "code/kotlin/org/example/c/domain1/dto").mkdirs()
        new File(projectDir, "code/kotlin/org/example/c/domain2/abc/defg").mkdirs()
        new File(projectDir, "code/kotlin/org/example/c/domain2/abc/defg").mkdirs()
        new File(projectDir, "code/kotlin/org/example/c/domain2/abc/Bar.kt").write("internal class Foo { }")
        new File(projectDir, "code/kotlin/org/example/c/domain2/dto").mkdirs()
        new File(projectDir, "settings.gradle") << ""
        new File(projectDir, "build.gradle") << """
            plugins {
                id "org.jetbrains.kotlin.jvm" version "1.3.61"
                id "org.jetbrains.kotlin.plugin.spring" version "1.3.61"
                id('io.polygonal')
            }
            
            polygonalArchitecture {
                sourcesDir = file('code/kotlin')
                basePackage = 'org.example.c'
                
                polygon {
                  packageDef {
                    name = ''
                    publicScope = -1
                  }
                
                  packageDef {
                    name = 'abc'
                    internalScope = -1
                  }
                
                  packageDef {
                    name = 'dto'
                  }
                  
                  packageDef {
                    name = 'abc.defg'
                    publicScope = -1
                  }
                }
            }
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("verifyPolygons")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("Task :verifyPolygons")
        !result.output.contains("ConditionException")

        cleanup:
        projectDir.deleteDir()
    }
}
