/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.polygonal

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

class PolygonalArchitecturePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder
                .builder().build()
        project.plugins.apply("java")

        when:
        project.plugins.apply("io.polygonal")

        then:
        project.tasks.findByName("verifyPolygons") != null
    }
}
