on:
  push:
    tags:
      - '*'
name: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: Deploy Release
        run: |
          chmod +x gradlew
          ./gradlew build -Pversion=$GITHUB_REF_NAME
          ./gradlew :plugin-gradle:publishPlugins -Pversion=$GITHUB_REF_NAME -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET
          ./gradlew publishMavenPublicationToSonatypeRepository -Pversion=$GITHUB_REF_NAME --stacktrace
        env:
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ secrets.GITHUB_REF_NAME }}
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          release_name: Release ${{ env.GITHUB_REF_NAME }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
